export const enum Types {
  PLAY = 'PLAY',
  PAUSE = 'PAUSE',
  PREVIOUS = 'PREVIOUS',
  NEXT = 'NEXT',
  SET_FAVORITES = 'SET_FAVORITES',
  ADD_FAVORITE = 'ADD_FAVORITE',
  DELETE_FAVORITE = 'DELETE_FAVORITE',
  DELETE_SONG = 'DELETE_SONG',
  ADD_TO_QUEUE = 'ADD_TO_QUEUE'
}